### ISSUE TITLE
Mover Drive pessoal para nuvem da UFOP

### ISSUE THREAD

**Issue by sdelabrida-ufop** [XR4GoodLab-UFOP/SiteLaboratorio#2]
Existe um drive neste link https://cutt.ly/rePvHy7 que está com sua propriedade. Vamos move-lo para o drive https://drive.google.com/drive/u/1/folders/1KuXU-oF-ssovYYXz0d83b-BwNbq9GnuL

**Comment by TulioAbreu** [comment]
As pastas foram movidas do drive anterior para o novo drive do lab.
Fecharei este issue por agora
