### ISSUE TITLE
Trocar logos do laboratório

### ISSUE THREAD

**Issue by sdelabrida-ufop** [XR4GoodLab-UFOP/SiteLaboratorio#6]
Favor trocar a logo nos site
ícones de aplicações 
Nos modelos de apresentações e documentos

**Comment by TulioAbreu** [comment]
@sdelabrida-ufop 

Consegui trocar as logos do site. Só para deixar registrado aqui para futura necessidade de mudar novamente:

- A maioria das logos é modificada em "Select Options" > "Logo" e simplesmente fazer o upload das logos novas
- A restante, no footer da página, é trocada em "Appearance" > "Widgets" > "Footer Column 1" > "Text". Será apresentado um código HTML correspondente ao footer, basta trocar o SRC da imagem da logo.

**Comment by TulioAbreu** [comment]
Vou fechar esta issue por enquanto, caso seja o caso de colocar um ícone novo para a favicon podemos criar outro.
